# نيكس-باكس بتاع Railway
[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && npm run start:prod"

[plan.variables]
DATABASE_URL = { value = "postgresql://postgres:kqwvEOLkjFysuvfnzUCjllvSidVqOJHp@ballast.proxy.rlwy.net:16198/railway" }
PORT = { value = "8001" }
JWT_SECRET = { value = "bucchain-super-secret-jwt-key-2025" }
JWT_REFRESH_SECRET = { value = "bucchain-super-secret-refresh-key-2025" }
NODE_ENV = { value = "production" }
